# Introduction to Pandas

In [3]:
pwd # Command to fnd out the working directory

'C:\\Users\\K2644037'

In [4]:
import numpy as np
import pandas as pd

In [5]:
#Command to find the current version of python
pd.__version__

'2.3.3'

In [6]:
index_1 =['Day 1', 'Day 2', 'Day 3']

In [7]:
data_1 = ['EDA', 'Ad EDA', 'Scipy' ]

In [11]:
np.random.seed(101)
data_2 = np.random.randint(0,101,(4,3))
data_2

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [12]:
#Command to create a dataframe
df = pd.DataFrame(data_2)
df

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [13]:
index_2 = ['q1', 'q2', 'q3', 'q4']

In [14]:
col_2= [ '2019','2020', '2021']

In [15]:
#Command to create a dataframe with specified labels as location indices
df_2 =pd.DataFrame(data_2,index=index_2, columns =col_2)
df_2

    2019  2020  2021
q1    95    11    81
q2    70    63    87
q3    75     9    77
q4    40     4    63

In [17]:
#Command to get the information about the dataframe
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, q1 to q4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2019    4 non-null      int32
 1   2020    4 non-null      int32
 2   2021    4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [18]:
#Command to get a certain row from the datframe using the index position
df_2.iloc[1]

2019    70
2020    63
2021    87
Name: q2, dtype: int32

In [19]:
type(df_2.iloc[1])

pandas.core.series.Series

In [20]:
#Command to get a certain row from the datframe using the labelled position
df_2.loc['q2']

2019    70
2020    63
2021    87
Name: q2, dtype: int32

In [21]:
Revenues_20_p1 = {'q1': [23, 12, 54, 36], 'q2': [42,58,13,65]}
Revenues_20_p2 = {'q3': [16, 44, 18, 38], 'q4': [8, 16, 47, 84]}

In [22]:
df_1=pd.DataFrame(Revenues_20_p1)
df_2=pd.DataFrame(Revenues_20_p2)

df_1

In [24]:
df_2

   q3  q4
0  16   8
1  44  16
2  18  47
3  38  84

### Concatentaing Dataframes

In [27]:
#command to concatenate 2 dataframes along columns
#concatenate means (link (things) together in a chain or series:)
pd.concat([df_1, df_2], axis=1)

   q1  q2  q3  q4
0  23  42  16   8
1  12  58  44  16
2  54  13  18  47
3  36  65  38  84

In [29]:
df_3=pd.concat([df_1, df_2], axis=0)

In [30]:
df_3

     q1    q2    q3    q4
0  23.0  42.0   NaN   NaN
1  12.0  58.0   NaN   NaN
2  54.0  13.0   NaN   NaN
3  36.0  65.0   NaN   NaN
0   NaN   NaN  16.0   8.0
1   NaN   NaN  44.0  16.0
2   NaN   NaN  18.0  47.0
3   NaN   NaN  38.0  84.0

In [31]:
df_3.iloc[1]

q1    12.0
q2    58.0
q3     NaN
q4     NaN
Name: 1, dtype: float64

In [33]:
df_3.index=range(len(df_3))
df_3

     q1    q2    q3    q4
0  23.0  42.0   NaN   NaN
1  12.0  58.0   NaN   NaN
2  54.0  13.0   NaN   NaN
3  36.0  65.0   NaN   NaN
4   NaN   NaN  16.0   8.0
5   NaN   NaN  44.0  16.0
6   NaN   NaN  18.0  47.0
7   NaN   NaN  38.0  84.0

### Merging Dataframes

In [34]:
Groups_1 = {'Gr_SN': [1, 2, 3, 4], 'Group_Name': ['X','Lions','Y','ABC']}
Groups_2 = {'Gr_ID': [12, 1, 3, 15], 'Group_Name': ['Lions', 'Dev', 'Y', 'ZZZ']}

In [35]:
G_df_1 = pd.DataFrame(Groups_1)
G_df_2 = pd.DataFrame(Groups_2)

In [36]:
G_df_1

   Gr_SN Group_Name
0      1          X
1      2      Lions
2      3          Y
3      4        ABC

In [37]:
G_df_2

   Gr_ID Group_Name
0     12      Lions
1      1        Dev
2      3          Y
3     15        ZZZ

In [39]:
#Command to merge one dataframe to another

#Inner Merge

pd.merge(G_df_1, G_df_2, how='inner', on='Group_Name')

   Gr_SN Group_Name  Gr_ID
0      2      Lions     12
1      3          Y      3

In [40]:
#Left Merge

pd.merge(G_df_1, G_df_2, how='left')

   Gr_SN Group_Name  Gr_ID
0      1          X    NaN
1      2      Lions   12.0
2      3          Y    3.0
3      4        ABC    NaN

### String Operations

In [42]:
libraries =pd.Series(['scipy', 'pandas', 'numpy', 'seaborn', 'matplotlib', '450'])

In [43]:
libraries

0         scipy
1        pandas
2         numpy
3       seaborn
4    matplotlib
5           450
dtype: object

In [44]:
#Command to change the string to uppercase
libraries.str.upper()

0         SCIPY
1        PANDAS
2         NUMPY
3       SEABORN
4    MATPLOTLIB
5           450
dtype: object

In [45]:
#Command to check whetehr value is digit
libraries.str.isdigit()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [46]:
lib = ['scipy, pandas, numpy','seaborn, matplotlib, sklearn']

In [48]:
lib_series = pd.Series(lib)
lib_series

0            scipy, pandas, numpy
1    seaborn, matplotlib, sklearn
dtype: object

In [49]:
#Command to split a string into a list of strings
lib_series.str.split(',')

0            [scipy,  pandas,  numpy]
1    [seaborn,  matplotlib,  sklearn]
dtype: object

In [50]:
lib_series.str.split(',', expand=True)

         0            1         2
0    scipy       pandas     numpy
1  seaborn   matplotlib   sklearn

In [51]:
type(lib_series.str.split(',', expand=True))

pandas.core.frame.DataFrame