In [1]:
import numpy as np
import pandas as pd

In [2]:
ls

 Volume in drive C is OS
 Volume Serial Number is 8C06-5FAC

 Directory of C:\Users\K2644037

06/10/2026  10:53    <DIR>          .
06/10/2026  10:03    <DIR>          ..
01/09/2026  14:42    <DIR>          .anaconda
06/10/2026  11:39    <DIR>          .conda
01/09/2026  14:42    <DIR>          .continuum
06/10/2026  11:25    <DIR>          .ipynb_checkpoints
06/10/2026  10:31    <DIR>          .ipython
06/10/2026  10:15    <DIR>          .ms-ad
06/10/2026  10:04    <DIR>          .msal
01/09/2026  14:42    <DIR>          .spyderpy3
06/10/2026  10:03                 0 .uc-9c4571f4e668fa18825d69d4813f7913.k2644037.pprsb3034-02.tmp
06/10/2026  11:26            34,521 06-10-2026.ipynb
06/10/2026  10:56            10,491 Code_Snippets_1.ipynb
06/10/2026  10:03    <DIR>          Contacts
01/04/2024  08:26    <DIR>          Desktop
06/10/2026  10:03    <DIR>          Documents
06/10/2026  10:38    <DIR>          Downloads
06/10/2026  10:03    <DIR>          Favorites
06/10/2026  10:14            56,877 imdb_top_1000_New-5.csv
06/10/2026  10:03    <DIR>          Links
01/04/2024  08:26    <DIR>          Music
11/08/2026  17:56    <DIR>          OneDrive
01/04/2024  08:26    <DIR>          Pictures
06/10/2026  11:27               617 Practice_06-10-2026.ipynb
06/10/2026  10:03    <DIR>          Saved Games
06/10/2026  10:03    <DIR>          Searches
01/04/2024  08:26    <DIR>          Videos
               5 File(s)        102,506 bytes
              22 Dir(s)  630,315,528,192 bytes free

In [6]:
#Command to load a csv file into the coding pipeline

df = pd.read_csv('imdb_top_1000_New-5.csv')
df

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710
...,...,...,...,...,...,...,...,...,...
896,Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300
897,Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705
898,Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207
899,Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621
900,Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   901 non-null    object
 1   Released_Year  901 non-null    object
 2   Certificate    901 non-null    object
 3   Runtime        901 non-null    object
 4   Runtime2       901 non-null    int64
 5   Genre          901 non-null    object
 6   IMDB_Rating    901 non-null    float64
 7   No_of_Votes    901 non-null    int64
 8   Gross          901 non-null    int64
dtypes: float64(1), int64(3), object(5)
memory usage: 63.5+ KB

In [8]:
#Command to see the first 5 rows of the dataset
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710

In [10]:
#first 8 rows

df.head(8)

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710
5,"Lock, Stock and Two Smoking Barrels",1998,A,107 min,107,Action,8.2,535216,3897569
6,Predator,1987,A,107 min,107,Action,7.8,371387,59735548
7,The Bourne Supremacy,2004,A,108 min,108,Action,7.7,434841,176241941

In [11]:
#Command to see last 5 rows

df.tail()

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross
896,Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300
897,Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705
898,Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207
899,Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621
900,Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424

In [13]:
#Comment for getting the statistical information (for the numerical features)

df.describe().transpose()# transpose - swap rows and colums

,count,mean,std,min,25%,50%,75%,max
Runtime2,901.0,1.237725e+02,2.788991e+01,45.0,104.0,120.0,137.0,321.0
IMDB_Rating,901.0,7.948391e+00,2.772287e-01,7.6,7.7,7.9,8.1,9.3
No_of_Votes,901.0,2.852698e+05,3.357608e+05,25088.0,58314.0,143434.0,400049.0,2343110.0
Gross,901.0,6.463583e+07,1.064970e+08,1305.0,2537520.0,20186659.0,75605492.0,936662225.0

### Working with columns

In [15]:
#Comment to extract desired single column

df['Released_Year']

0      2003
1      2011
2      1973
3      1971
4      1971
       ...
896    1959
897    2013
898    1982
899    1962
900    1944
Name: Released_Year, Length: 901, dtype: object

In [16]:
# Code to extract multiple desired columns

cols = ['Series_Title', 'IMDB_Rating']
df[cols] # or df[['Series_Title', 'IMDB_Rating']]

              Series_Title  IMDB_Rating
0                 Oldeuboi          8.4
1             Serbuan maut          7.6
2         Enter the Dragon          7.7
3              Dirty Harry          7.7
4    The French Connection          7.7
..                     ...          ...
896    Hiroshima mon amour          7.9
897                Gravity          7.7
898   Pink Floyd: The Wall          8.1
899        Ivanovo detstvo          8.1
900               Lifeboat          7.6

[901 rows x 2 columns]

In [25]:
#Command to create a new column and fill with values

df['Runtime_in_hours'] = df['Runtime2']/60
df

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.683333
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.683333
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.700000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.700000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710,1.733333
...,...,...,...,...,...,...,...,...,...,...
896,Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300,1.500000
897,Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705,1.516667
898,Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207,1.583333
899,Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621,1.583333
900,Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.616667

In [37]:
#command to round the value to 2 decimals

df['Runtime_in_hours'] = np.round(df['Runtime2']/60, 2)
df

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Series_Title,,,,,,,,,
Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.68
Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.68
Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.70
Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.70
The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710,1.73
...,...,...,...,...,...,...,...,...,...
Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300,1.50
Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705,1.52
Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207,1.58
Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621,1.58
Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.62

In [29]:
#Command for overwriting any specified column
#df['Gross'] = df['No_of_Votes']*3

In [27]:
#Command to drop a column
df.drop('Runtime_in_hours', axis=1)

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710
...,...,...,...,...,...,...,...,...,...
896,Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300
897,Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705
898,Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207
899,Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621
900,Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424

In [28]:
df

,Series_Title,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
0,Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.683333
1,Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.683333
2,Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.700000
3,Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.700000
4,The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710,1.733333
...,...,...,...,...,...,...,...,...,...,...
896,Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300,1.500000
897,Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705,1.516667
898,Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207,1.583333
899,Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621,1.583333
900,Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.616667

In [ ]:
# df= df.drop('Runtime_in_hours', axis=1)
#     or
#df.drop('Runtime_in_hours', axis = 1, inplace = true)

### Working with Rows

In [39]:
df = df.set_index('Series_Title')
df
#SeriesTItle is not on the same row as the other column names as it is now a labelled index not a co

KeyError: "None of ['Series_Title'] are in the columns"

In [31]:
df.iloc[0]

Released_Year           2003
Certificate                A
Runtime              101 min
Runtime2                 101
Genre                 Action
IMDB_Rating              8.4
No_of_Votes           515451
Gross                 707481
Runtime_in_hours    1.683333
Name: Oldeuboi, dtype: object

In [33]:
df.loc['Oldeuboi']

Released_Year           2003
Certificate                A
Runtime              101 min
Runtime2                 101
Genre                 Action
IMDB_Rating              8.4
No_of_Votes           515451
Gross                 707481
Runtime_in_hours    1.683333
Name: Oldeuboi, dtype: object

In [40]:
#Slicing to get a certain set of data

df.iloc[0:4]

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Series_Title,,,,,,,,,
Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.68
Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.68
Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.70
Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.70

### Condtitional Filtering

In [35]:
df['IMDB_Rating']>8

Series_Title
Oldeuboi                  True
Serbuan maut             False
Enter the Dragon         False
Dirty Harry              False
The French Connection    False
                         ...
Hiroshima mon amour      False
Gravity                  False
Pink Floyd: The Wall      True
Ivanovo detstvo           True
Lifeboat                 False
Name: IMDB_Rating, Length: 901, dtype: bool

In [41]:
df[df['IMDB_Rating']>8.8]

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Series_Title,,,,,,,,,
The Lord of the Rings: The Return of the King,2003,U,201 min,201,Action,8.9,1642758,377845905,3.35
The Dark Knight,2008,UA,152 min,152,Action,9.0,2303232,534858444,2.53
Schindler's List,1993,A,195 min,195,Biography,8.9,1213505,96898818,3.25
Pulp Fiction,1994,A,154 min,154,Crime,8.9,1826188,107928762,2.57
The Godfather,1972,A,175 min,175,Crime,9.2,1620367,134966411,2.92
The Godfather: Part II,1974,A,202 min,202,Crime,9.0,1129952,57300000,3.37
12 Angry Men,1957,U,96 min,96,Crime,9.0,689845,4360000,1.60
The Shawshank Redemption,1994,A,142 min,142,Drama,9.3,2343110,28341469,2.37

In [42]:
df[df['Genre']=='Action']

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Series_Title,,,,,,,,,
Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.68
Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.68
Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.70
Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.70
The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710,1.73
...,...,...,...,...,...,...,...,...,...
Baahubali 2: The Conclusion,2017,UA,167 min,167,Action,8.2,75348,20186659,2.78
The Lord of the Rings: The Two Towers,2002,UA,179 min,179,Action,8.7,1485555,342551365,2.98
Avengers: Endgame,2019,UA,181 min,181,Action,8.4,809955,858373000,3.02
The Warriors,1979,UA,92 min,92,Action,7.6,93878,22490039,1.53
Kung fu,2004,UA,99 min,99,Action,7.7,127250,17108591,1.65

In [46]:
df[ (df['IMDB_Rating']>8.8) & (df['Genre']=='Action')]

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Series_Title,,,,,,,,,
The Lord of the Rings: The Return of the King,2003,U,201 min,201,Action,8.9,1642758,377845905,3.35
The Dark Knight,2008,UA,152 min,152,Action,9.0,2303232,534858444,2.53

### Useful Functitons

In [ ]:
'''
for adding another column 'Stars' based on the IMBD_Rating
>9, *****
>8, ****
otherwise, ***
'''

In [50]:
# Custom function creation - example
# Function to assign stars based on the IMDB_Rating
def starts_fn(rating):
    if rating > 9:
        return "*****"
    elif rating > 8:
        return "****"
    else: return "***"

In [52]:
#Command for using apply function
df['Stars'] = df['IMDB_Rating'].apply(starts_fn)
df

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours,Stars
Series_Title,,,,,,,,,,
Oldeuboi,2003,A,101 min,101,Action,8.4,515451,707481,1.68,****
Serbuan maut,2011,A,101 min,101,Action,7.6,190531,4105123,1.68,***
Enter the Dragon,1973,A,102 min,102,Action,7.7,96561,25000000,1.70,***
Dirty Harry,1971,A,102 min,102,Action,7.7,143292,35900000,1.70,***
The French Connection,1971,A,104 min,104,Action,7.7,110075,15630710,1.73,***
...,...,...,...,...,...,...,...,...,...,...
Hiroshima mon amour,1959,UA,90 min,90,Drama,7.9,28421,88300,1.50,***
Gravity,2013,UA,91 min,91,Drama,7.7,769145,274092705,1.52,***
Pink Floyd: The Wall,1982,UA,95 min,95,Drama,8.1,76081,22244207,1.58,****
Ivanovo detstvo,1962,UA,95 min,95,Drama,8.1,31728,102621,1.58,****
Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.62,***

In [54]:
#Sort values based on a certain value

df.sort_values('IMDB_Rating',ascending =False)

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours,Stars
Series_Title,,,,,,,,,,
The Shawshank Redemption,1994,A,142 min,142,Drama,9.3,2343110,28341469,2.37,*****
The Godfather,1972,A,175 min,175,Crime,9.2,1620367,134966411,2.92,*****
The Dark Knight,2008,UA,152 min,152,Action,9.0,2303232,534858444,2.53,****
12 Angry Men,1957,U,96 min,96,Crime,9.0,689845,4360000,1.60,****
The Godfather: Part II,1974,A,202 min,202,Crime,9.0,1129952,57300000,3.37,****
...,...,...,...,...,...,...,...,...,...,...
Harry Potter and the Sorcerer's Stone,2001,U,152 min,152,Adventure,7.6,658185,317575550,2.53,***
The Muppet Movie,1979,U,95 min,95,Adventure,7.6,32802,76657000,1.58,***
The Long Goodbye,1973,A,112 min,112,Comedy,7.6,26337,959000,1.87,***
The Royal Tenenbaums,2001,A,110 min,110,Comedy,7.6,266842,52364010,1.83,***
Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.62,***

In [57]:
#Sort values based on multiple value
df.sort_values(['IMDB_Rating','No_of_Votes'],ascending =False)

,Released_Year,Certificate,Runtime,Runtime2,Genre,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours,Stars
Series_Title,,,,,,,,,,
The Shawshank Redemption,1994,A,142 min,142,Drama,9.3,2343110,28341469,2.37,*****
The Godfather,1972,A,175 min,175,Crime,9.2,1620367,134966411,2.92,*****
The Dark Knight,2008,UA,152 min,152,Action,9.0,2303232,534858444,2.53,****
The Godfather: Part II,1974,A,202 min,202,Crime,9.0,1129952,57300000,3.37,****
12 Angry Men,1957,U,96 min,96,Crime,9.0,689845,4360000,1.60,****
...,...,...,...,...,...,...,...,...,...,...
Nelyubov,2017,R,127 min,127,Drama,7.6,29765,566356,2.12,***
On Golden Pond,1981,UA,109 min,109,Drama,7.6,27650,119285432,1.82,***
Omohide poro poro,1991,U,118 min,118,Animation,7.6,27071,453243,1.97,***
Lifeboat,1944,UA,97 min,97,Drama,7.6,26471,13780424,1.62,***
The Long Goodbye,1973,A,112 min,112,Comedy,7.6,26337,959000,1.87,***

In [58]:
#function to finf the minumum value of a feature
df['Runtime2'].min()

45

In [59]:
#Function to get the labelled index of the minimum value of a feature
df['Runtime2'].idxmin()

'Sherlock Jr.'

In [60]:
#Command to get the count of classes in a feature/column

df['Genre'].value_counts()

Genre
Drama        270
Action       167
Comedy       140
Crime        104
Biography     82
Animation     74
Adventure     64
Name: count, dtype: int64

In [61]:
df['Certificate'].value_counts()

Certificate
U         233
A         230
UA        220
R         145
PG-13      42
Passed     31
Name: count, dtype: int64

In [62]:
df['Released_Year'].value_counts()

Released_Year
2014    31
2004    30
2013    28
2007    26
2016    26
        ..
1938     1
1921     1
1924     1
PG       1
1932     1
Name: count, Length: 95, dtype: int64

In [64]:
df = df[ df['Released_Year']!='PG']

In [65]:
df['Released_Year'].value_counts()

Released_Year
2014    31
2004    30
2013    28
2007    26
2016    26
        ..
1926     1
1938     1
1921     1
1924     1
1932     1
Name: count, Length: 94, dtype: int64

In [67]:
df['Released_Year'] = df['Released_Year'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 900 entries, Oldeuboi to Lifeboat
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Released_Year     900 non-null    int64
 1   Certificate       900 non-null    object
 2   Runtime           900 non-null    object
 3   Runtime2          900 non-null    int64
 4   Genre             900 non-null    object
 5   IMDB_Rating       900 non-null    float64
 6   No_of_Votes       900 non-null    int64
 7   Gross             900 non-null    int64
 8   Runtime_in_hours  900 non-null    float64
 9   Stars             900 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 109.6+ KB

In [68]:
#Groupby function based on a cerain feature/column

df.groupby('Released_Year').mean(numeric_only=True)

,Runtime2,IMDB_Rating,No_of_Votes,Gross,Runtime_in_hours
Released_Year,,,,,
1921,68.000000,8.300000,113314.000000,5.450000e+06,1.130000
1924,45.000000,8.200000,41985.000000,9.773750e+05,0.750000
1925,85.000000,8.100000,77053.500000,2.750485e+06,1.415000
1926,67.000000,8.100000,81156.000000,1.033895e+06,1.120000
1927,123.500000,8.200000,103428.500000,8.878530e+05,2.060000
...,...,...,...,...,...
2016,125.192308,7.934615,248171.538462,1.047822e+08,2.087692
2017,122.428571,7.900000,247483.047619,8.985490e+07,2.040000
2018,129.555556,8.016667,223890.222222,1.443510e+08,2.159444
2019,132.136364,7.981818,270438.227273,1.131671e+08,2.201364
2020,126.666667,8.133333,84127.000000,4.512098e+06,2.111667

In [69]:
#Groupby function based on multiple features/columns

df.groupby(['Released_Year','Genre']).mean(numeric_only=True).tail(20)

                           Runtime2  IMDB_Rating    No_of_Votes         Gross  \
Released_Year Genre
2017          Comedy     115.000000     8.200000  432610.000000  5.451374e+07
              Crime      107.000000     7.700000  205444.000000  3.380086e+07
              Drama      114.666667     7.733333  100726.833333  3.035434e+07
2018          Action     141.166667     8.000000  284964.666667  2.064419e+08
              Animation  112.000000     7.966667  254760.333333  2.769461e+08
              Biography  132.000000     8.100000  414116.500000  1.507541e+08
              Comedy     124.000000     8.000000   27978.000000  1.034095e+06
              Crime      130.000000     8.100000   67314.500000  2.343728e+06
              Drama      125.250000     8.000000  141278.750000  5.539976e+07
2019          Action     148.666667     8.100000  446212.000000  3.261783e+08
              Adventure  105.000000     7.800000   51951.000000  6.831291e+06
              Animation   98.000000     8.000000  153969.000000  2.171903e+08
              Biography  157.333333     7.700000  143955.666667  2.799162e+07
              Comedy     135.166667     8.016667  356124.166667  6.074641e+07
              Crime      122.000000     8.500000  939252.000000  3.354513e+08
              Drama      130.000000     8.000000  138260.200000  5.583867e+07
2020          Animation  100.000000     8.100000  159171.000000  1.467787e+07
              Biography  160.000000     8.600000   55291.000000  1.256300e+04
              Comedy     109.000000     7.850000   72704.500000  5.073270e+06
              Drama      141.000000     8.200000   72445.500000  1.117805e+06

                         Runtime_in_hours
Released_Year Genre
2017          Comedy             1.920000
              Crime              1.780000
              Drama              1.910000
2018          Action             2.351667
              Animation          1.866667
              Biography          2.200000
              Comedy             2.070000
              Crime              2.170000
              Drama              2.087500
2019          Action             2.476667
              Adventure          1.750000
              Animation          1.635000
              Biography          2.620000
              Comedy             2.251667
              Crime              2.030000
              Drama              2.166000
2020          Animation          1.670000
              Biography          2.670000
              Comedy             1.815000
              Drama              2.350000